### ISSUE TITLE
Feature flag support

### ISSUE THREAD

**Issue by gnzlbg** [rust-dev-tools/rust-semverver#91]
To test libc we need to also support building a crate with `--features` and with `--no-default-features`.

**Comment by gnzlbg** [comment]
Or are --features and --no-default-features already read by `cargo` ? The `cargo::utils::Config` takes an `env` variable, which might result in the args being read.

**Comment by ibabushkin** [comment]
Well, the issue is that we currently cannot really pass anything to cargo's CLI frontend from our code, as the implementation is private and doesn't directly generate a `Config` afaict. I'm also not sure how passing environment to the config would help with forcing cargo to honour flags we have no way of passing atm. Am I missing something?

**Comment by gnzlbg** [comment]
cc @ehuss

**Comment by ibabushkin** [comment]
To summarize the implementation: we basically can pass `--features` and `--all-features` over the same channel as `--no-default-features` to cargo's `CompileOptions`, which I seem to have missed previously.
